services:
  # API service
  - type: web
    name: money-transfer-comparison
    env: node
    buildCommand: npm install && npm run install-client && npm run build-client
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: WISE_CLIENT_ID
        sync: false
      - key: WISE_CLIENT_KEY
        sync: false
      - key: WISE_CLIENT_SECRET
        sync: false
      - key: WISE_API_URL
        value: https://api.wise.com
      - key: PUBLIC_URL
        value: /
      - key: REACT_APP_API_URL
        value: /
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /sitemap.xml
        name: Content-Type
        value: application/xml
      - path: /robots.txt
        name: Content-Type
        value: text/plain
      - path: /google-site-verification.html
        name: Content-Type
        value: text/html
      - path: /static/js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /static/css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /static/media/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /images/*
        name: Cache-Control
        value: public, max-age=604800
      - path: /favicon.ico
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /health