// Auto-generated ratings mapper
// Created on 2023-05-13T16:30:00.000Z
// This file helps the frontend map provider names to their ratings

export const trustpilotRatingsMap = {
  "starlingbank": 4.5,
  "provider-starlingbank": 4.5,
  "profee": 4.4,
  "provider-profee": 4.4,
  "wise": 4.3,
  "provider-wise": 4.3,
  "torfx": 4.4,
  "provider-torfx": 4.4,
  "tor": 4.4,
  "tor-fx": 4.4,
  "tor fx": 4.4,
  "instarem": 4.1,
  "provider-instarem": 4.1,
  "xe": 4.2,
  "provider-xe": 4.2,
  "xemoney": 4.2,
  "xe-money": 4.2,
  "xoom": 4,
  "provider-xoom": 4,
  "remitly": 4.5,
  "provider-remitly": 4.5,
  "westernunion": 4.5,
  "provider-westernunion": 4.5,
  "monese": 4,
  "provider-monese": 4,
  "ofx": 4.4,
  "provider-ofx": 4.4,
  "rbs": 1.5,
  "provider-rbs": 1.5,
  "moneygram": 4.5,
  "provider-moneygram": 4.5,
  "natwest": 1.5,
  "provider-natwest": 1.5,
  "barclays": 2,
  "provider-barclays": 2,
  "lloyds": 1.5,
  "provider-lloyds": 1.5,
  "halifax": 1.5,
  "provider-halifax": 1.5,
  "paypal": 1.5,
  "provider-paypal": 1.5,
  "nationwide": 2,
  "provider-nationwide": 2,
  "chase": 3.8,
  "provider-chase": 3.8,
  "skrill": 4.4,
  "provider-skrill": 4.4,
  "regencyfx": 4.9,
  "provider-regencyfx": 4.9,
  "regency": 4.9,
  "regency-fx": 4.9,
  "regency fx": 4.9,
  "pandaremit": 4.1,
  "provider-pandaremit": 4.1,
  "panda": 4.1,
  "panda-remit": 4.1,
  "panda remit": 4.1,
  "worldremit": 3.9,
  "provider-worldremit": 3.9,
  "currencyfair": 4.4,
  "provider-currencyfair": 4.4,
  "revolut": 4.4,
  "provider-revolut": 4.3,
  "transfergo": 4.3,
  "provider-transfergo": 4.3
};
